version: "3"

services:
  pg:
    image: postgres:13.4-alpine
    environment:
      POSTGRES_PASSWORD: 'example'
      POSTGRES_USER: 'postgres'
      POSTGRES_DB: 'timesheets-develop'
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4:6.5
    ports:
      - "3081:80"
    environment:
      PGADMIN_DEFAULT_PASSWORD: 'example'
      PGADMIN_DEFAULT_EMAIL: 'al.shreyner@gmail.com'
